### ISSUE TITLE
The when sections behaves strangely when clicking on the "terminal" section.

### ISSUE THREAD

**Issue by romu42** [dotse/edudig#79]
The when section increases in time when the terminal section is clicked on. 
The when section needs a place holder for the digits:
`;; WHEN: Wed Mar 29 17:7:19 CET 2023`

**Comment by FridaDahl** [comment]
Solution, get date from responseheader instead of creating one.

**Comment by romu42** [comment]
Offline discussion: We have will send a Timestamp from the backend with the query response.

**Comment by romu42** [comment]
@FridaDahl Backend returns a timestamp string in the respons now:


``` Json
    "Round trip time": 56294786,
    "Timestamp": "Mon Apr 24 10:33:53 CET 2023",
    "Transport": "udp",
    "Zone": "catch22.se"
```
