### ISSUE TITLE
Make RRType in answer, authority and additional section clickable and link appropriate info section

### ISSUE THREAD

**Issue by FridaDahl** [dotse/edudig#93]

**Comment by romu42** [comment]
SOA RR

{
  "Title": "SOA: Source Of Authority",
  "Paragraphs": [
  "The data in the SOA RR describes the management of the zone.",
  ]
}

**Comment by romu42** [comment]
A RR

{
"Title": "A: A host address",
"Paragraphs": [
"The ip address for a host.",
]
}
